apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform
  namespace: ai-os-staging
spec:
  replicas: 3
  selector:
    matchLabels:
      app: platform
  template:
    metadata:
      labels:
        app: platform
    spec:
      containers:
        - name: platform
          image: aiosregistry-akfrawasefd6djbz.azurecr.io/aios-backend:test323
          envFrom:
            - secretRef:
                name: staging-env
          ports:
            - containerPort: 8000
